CreditTeam/CreditTeam/Controllers/FacultyController.cs
using System.Collections.Generic;
using AutoMapper;
using CreditTeam.Models.Entity.School;
using CreditTeam.Models.ViewModel.School;
using CreditTeam.Service.SchoolService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CreditTeam.Controllers
{
    [Authorize]
    public class FacultyController : Controller
    {
        private readonly IFacultyService _facultyService;
        private readonly IClassRoomService _classRoomService;
        private readonly IMapper _mapper;

        public FacultyController(IFacultyService facultyService, IClassRoomService classRoomService, IMapper mapper)
        {
            _facultyService = facultyService;
            _classRoomService = classRoomService;
            _mapper = mapper;
        }


        [HttpGet]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Index()
        {
            var faculities = _facultyService.GetAll();
            var model = _mapper.Map<IEnumerable<ListFacultyViewModel>>(faculities);
            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Create()
        {
            IEnumerable<ClassRoom> classrooms = _classRoomService.GetAll();
            ViewData["ClassRoomId"] = new SelectList(classrooms, "Id", "Name");
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Create(AddEditFacultyViewModel facultyViewModel)
        {
            if (ModelState.IsValid)
            {
                var faculties = _mapper.Map<Faculty>(facultyViewModel);
                _facultyService.Add(faculties);
                _facultyService.Save();
                return RedirectToAction("Index");
            }

            IEnumerable<ClassRoom> classrooms = _classRoomService.GetAll();
            ViewData["ClassRoomId"] = new SelectList(classrooms, "Id", "Name");
            return View();
        }

        [HttpGet]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Edit(int id)
        {
            var faculties = _facultyService.GetById(id);
            IEnumerable<ClassRoom> classrooms = _classRoomService.GetAll();
            ViewData["ClassRoomId"] = new SelectList(classrooms, "Id", "Name", faculties.Id);
            var model = _mapper.Map<AddEditFacultyViewModel>(faculties);
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Edit(AddEditFacultyViewModel facultyViewModel)
        {
            var faculties = _mapper.Map<Faculty>(facultyViewModel);
            _facultyService.Update(faculties);
            _facultyService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Delete(int id)
        {
            _facultyService.Delete(id);
            _facultyService.Save();
            return RedirectToAction("Index");
        }
    }
}

CreditTeam/CreditTeam/Controllers/PointController.cs
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using CreditTeam.Models.Entity.School;
using CreditTeam.Models.Entity.User;
using CreditTeam.Models.ViewModel.School;
using CreditTeam.Service.SchoolService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CreditTeam.Controllers
{
    [Authorize]
    public class PointController : Controller
    {
        private readonly IPointService _pointService;
        private readonly IDisciplineService _disciplineService;
        private readonly UserManager<User> _userManager;
        private readonly IMapper _mapper;

        public PointController(IPointService pointService, IDisciplineService disciplineService,
            UserManager<User> userManager, IMapper mapper)
        {
            _pointService = pointService;
            _disciplineService = disciplineService;
            _userManager = userManager;
            _mapper = mapper;
        }

        [HttpGet]
        [Authorize(Policy = "pointpolicy")]
        public IActionResult Index()
        {
            var listpoint = from point in _pointService.GetAll()
                join user in _userManager.Users.ToList() on point.UserId equals user.Id
                select new ListPointViewModel
                {
                    Id = point.Id,
                    ComponentScore = point.ComponentScore,
                    FinalExam0 = point.FinalExam0,
                    FinalExam1 = point.FinalExam1,
                    ScoreByScale010 = point.ScoreByScale010,
                    ScoreByScale04 = point.ScoreByScale04,
                    ScoreByabcdf = point.ScoreByabcdf,
                    DisciplineName = point.Discipline.Name,
                    StudentName = user.FullName
                };
            return View(listpoint.ToList());
        }

        [HttpGet]
        [Authorize(Policy = "pointpolicy")]
        public IActionResult Create()
        {
            IEnumerable<Discipline> disciplines = _disciplineService.GetAll();
            ViewData["DisciplineId"] = new SelectList(disciplines, "Id", "Name");
            IEnumerable<User> users = _userManager.Users.ToList();
            ViewData["UserId"] = new SelectList(users, "Id", "FullName");
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "pointpolicy")]
        public IActionResult Create(AddEditPointViewModel pointViewModel)
        {
            if (ModelState.IsValid)
            {
                var point = _mapper.Map<Point>(pointViewModel);
                _pointService.Add(point);
                _pointService.Save();
                return RedirectToAction("Index");
            }

            IEnumerable<Discipline> disciplines = _disciplineService.GetAll();
            ViewData["DisciplineId"] = new SelectList(disciplines, "Id", "Name");
            IEnumerable<User> users = _userManager.Users.ToList();
            ViewData["UserId"] = new SelectList(users, "Id", "FullName");
            return View();
        }

        [HttpGet]
        [Authorize(Policy = "pointpolicy")]
        public IActionResult Edit(int id)
        {
            var point = _pointService.GetById(id);
            var model = _mapper.Map<EditPointViewModel>(point);
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "pointpolicy")]
        public IActionResult Edit(EditPointViewModel pointViewModel)
        {
            var point = _mapper.Map<Point>(pointViewModel);
            _pointService.Update(point);
            _pointService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Policy = "pointpolicy")]
        public IActionResult Delete(int id)
        {
            _pointService.Delete(id);
            _pointService.Save();
            return RedirectToAction("Index");
        }
    }
}

CreditTeam/CreditTeam/Controllers/RoleController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using CreditTeam.Models.Entity.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CreditTeam.Controllers
{
    [Authorize]
    public class RoleController : Controller
    {
        private readonly RoleManager<Role> _roleManager;

        public RoleController(RoleManager<Role> roleManager)
        {
            _roleManager = roleManager;
        }

        [Authorize(Policy = "writepolicy")]
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        [Authorize(Policy = "writepolicy")]
        public IActionResult Create()
        {
            return View(new Role());
        }

        [HttpPost]
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Create(Role role)
        {
            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
    }
}

CreditTeam/CreditTeam/Controllers/SemesterController.cs
using System.Collections.Generic;
using AutoMapper;
using CreditTeam.Models.Entity.School;
using CreditTeam.Models.ViewModel.School;
using CreditTeam.Service.SchoolService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CreditTeam.Controllers
{
    [Authorize]
    public class SemesterController : Controller
    {
        private readonly ISemesterService _semesterService;
        private readonly IMapper _mapper;

        public SemesterController(ISemesterService semesterService, IMapper mapper)
        {
            _semesterService = semesterService;
            _mapper = mapper;
        }

        [HttpGet]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Index()
        {
            var semester = _semesterService.GetAll();
            var model = _mapper.Map<IEnumerable<ListSemesterViewModel>>(semester);
            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Create(AddEditSemesterViewModel semesterViewModel)
        {
            if (ModelState.IsValid)
            {
                var semester = _mapper.Map<Semester>(semesterViewModel);
                _semesterService.Add(semester);
                _semesterService.Save();
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Edit(int id)
        {
            var semester = _semesterService.GetById(id);
            var model = _mapper.Map<AddEditSemesterViewModel>(semester);
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Edit(AddEditSemesterViewModel semesterViewModel)
        {
            var semester = _mapper.Map<Semester>(semesterViewModel);
            _semesterService.Update(semester);
            _semesterService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Policy = "writepolicy")]
        public IActionResult Delete(int id)
        {
            _semesterService.Delete(id);
            _semesterService.Save();
            return RedirectToAction("Index");
        }
    }
}

CreditTeam/CreditTeam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CreditTeam</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CreditTeam</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ClassRoom" asp-action="Index">ClassRoom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faculty" asp-action="Index">Faculty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Discipline" asp-action="Index">Discipline</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Point" asp-action="Index">Point</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Semester" asp-action="Index">Semester</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - CreditTeam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

CreditTeam/CreditTeam/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>Dashio - Bootstrap Admin Template</title>

  <!-- Favicons -->
  <link href="~/teamCreditCss/img/favicon.png" rel="icon">
  <link href="~/teamCreditCss/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Bootstrap core CSS -->
  <link href="~/teamCreditCss/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!--external css-->
  <link href="~/teamCreditCss/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="~/teamCreditCss/css/style.css" rel="stylesheet">
  <link href="~/teamCreditCss/css/style-responsive.css" rel="stylesheet">
  
  <!-- =======================================================
    Template Name: Dashio
    Template URL: https://templatemag.com/dashio-bootstrap-admin-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>
  <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
@RenderBody()
  <!-- js placed at the end of the document so the pages load faster -->
  <script src="~/teamCreditCss/lib/jquery/jquery.min.js"></script>
  <script src="~/teamCreditCss/lib/bootstrap/js/bootstrap.min.js"></script>
  <!--BACKSTRETCH-->
  <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
  <script type="text/javascript" src="~/teamCreditCss/lib/jquery.backstretch.min.js"></script>
  <script>
    $.backstretch("/teamCreditCss/img/login-bg.jpg", {
      speed: 500
    });
  </script>
</body>

</html>